CREATE TABLE USER(DOMAIN VARCHAR(20), USERID VARCHAR(20), PASSWORD_HASH VARCHAR(100) NOT NULL, NAME VARCHAR(100) NOT NULL, ROLE VARCHAR(20) NOT NULL, PHONE VARCHAR(20), EMAIL VARCHAR(100), ISACTIVE BIT, PRIMARY KEY (DOMAIN, USERID));

